env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-essential
  - xo
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
  - prettier
globals:
  L: readonly
rules:
  camelcase: off
  default-case: off
  no-alert: off
  guard-for-in: off
  vue/no-side-effects-in-computed-properties: off
  prettier/prettier: error
