env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-essential
  - xo
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
  - prettier
rules: {}
